/**
 * THIS FILE IS GENERATED BY jsonrpcstub, DO NOT CHANGE IT!!!!!
 */

#ifndef _MYSTUBNAME_H_
#define _MYSTUBNAME_H_

#include <jsonrpc/clientconnector.h>
#include <jsonrpc/client.h>
#include <string>
#include <json/json.h>

class MyStubName
{
    public:
        MyStubName(jsonrpc::ClientConnector* conn)
        {
            this->client = new jsonrpc::Client(conn,false);
        }
        ~MyStubName()
        {
            delete this->client;
        }

        Json::Value sayHello(const std::string& name)
        {
            Json::Value p;
            p["name"] = name; 

            return this->client->CallMethod("sayHello",p);
        }

        void notifyServer()
        {
            Json::Value p;
            
            this->client->CallMethod("notifyServer",p);
        }

    private:
        jsonrpc::Client* client;
};
#endif //_MYSTUBNAME_H_
