/**
 * THIS FILE IS GENERATED BY jsonrpcstub, DO NOT CHANGE IT!!!!!
 */

#ifndef _MYSTUBCLIENT_H_
#define _MYSTUBCLIENT_H_

#include <jsonrpc/rpc.h>

class MyStubClient
{
    public:
        MyStubClient(jsonrpc::AbstractClientConnector* conn)
        {
            this->client = new jsonrpc::Client(conn);
        }
        ~MyStubClient()
        {
            delete this->client;
        }

        void notifyServer() throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            
            this->client->CallNotification("notifyServer",p);
        }

        std::string sayHello(const std::string& name) throw (jsonrpc::JsonRpcException)
        {
            Json::Value p;
            p["name"] = name; 

            return this->client->CallMethod("sayHello",p).asString();
        }

    private:
        jsonrpc::Client* client;
};
#endif //_MYSTUBCLIENT_H_
