version: 2.1
orbs:
  codecov: codecov/codecov@1.0.2
jobs:
  "build-linux-gcc":
    docker:
      - image: "debian:latest"
    steps:
      - checkout
      - run:
          name: Installing Dependencies
          command: ./docker/deps-debian.sh
      - run:
          name: Build test and install
          command: 'OS=debian ./docker/build_test_install.sh'
      - run:
          name: Create coverage report
          command: lcov --directory . --capture --output-file coverage.info && lcov --remove coverage.info '/usr/*' --output-file coverage.info
      - codecov/upload:
          file: coverage.info
  "build-osx-clang":
    macos:
      xcode: "13.0.0"
    steps:
      - checkout
      - run:
          name: Installing CMake
          command: 'brew install cmake jsoncpp argtable curl hiredis redis libmicrohttpd'
      - run:
          name: Build
          command: 'OS=osx ./docker/build_test_install.sh'
workflows:
  version: 2
  build:
    jobs:
      - "build-linux-gcc"
      - "build-osx-clang"