#ifndef CLIENTTEMPLATE_CLIENT_H_
#define CLIENTTEMPLATE_CLIENT_H_

#define TEMPLATE_CLIENT_METHOD "\
        <return_type> <methodname>(<parameters>) throw (jsonrpc::JsonRpcException)\n\
        {\n\
            Json::Value p;\n\
            <parameter_assign>\n\
            <return_statement>\n\
        }\n\
"

#define TEMPLATE_CLIENT_STUB "\
/**\n\
 * THIS FILE IS GENERATED BY jsonrpcstub, DO NOT CHANGE IT!!!!!\n\
 */\n\
\n\
#ifndef _<STUBNAME>_H_\n\
#define _<STUBNAME>_H_\n\
\n\
#include <jsonrpc/rpc.h>\n\
\n\
class <stubname>\n\
{\n\
    public:\n\
        <stubname>(jsonrpc::AbstractClientConnector* conn)\n\
        {\n\
            this->client = new jsonrpc::Client(conn);\n\
        }\n\
        ~<stubname>()\n\
        {\n\
            delete this->client;\n\
        }\n\n\
<methods>\
    private:\n\
        jsonrpc::Client* client;\n\
};\n\
#endif //_<STUBNAME>_H_\n\
"

#endif
